aws-quickstart/quickstart-atlassian-jira

templates/JiraDataCenter.template
templates/quickstart-jira-master.template

AZ parameters removed as they not actually required.
Database name hardcoded to be on par with BitBucket template.
quick-start template updated to put cluster nodes into private networks.
Database creation moved to AMI. Multi AZ support added to JIRA template.

JIRA private network support and less significant changes

---

templates/JiraDataCenter.template
templates/quickstart-jira-master.template

Also, new AMI with links to updated location in scripts has been published.

JIRA's installers has been moved into proper location.

---

templates/JiraDataCenter.template
templates/quickstart-jira-master.json
templates/quickstart-jira-master.template

We are replacing version parameter with product parameter in template. 
Our plan is to make template install only the latest versions of the products. 
As MVP we have hardcoded specific versions that are uploaded to Atlassian S3 bucket.

Adding JIRA ServiceDesk and JIRA Core as options to install

---

templates/JiraDataCenter.template

One more time.
I've updated my forked template and now have everything set up right.
We've discovered that [JIRA gadgets break when user tries to access a stack installed from the template with custom domain name](https://jira.atlassian.com/browse/JRASERVER-65486). For gadgets to work user needs to go into tomcat's server.xml and adjust 'proxyName' value to match that custom domain name. Currently template sets it into ELB DNS name so I've added possibility to specify custom string to use as 'proxyName'.
Please note that JiraDataCenter template has new optional parameter now, probably you want to add this parameter into Quick Start template.

Quick start template for jira data center on aws should allow configuration of custom dns name

---

templates/quickstart-jira-master.template

I tried to use the Jira Quickstart and encountered an issue when trying to use SSL certificates set up with ACM. Looking into the templates used by the quickstart we noticed that it assume the certificate to be an IAM one, but this is not documented anywhere. Moreover, IAM certificates needs to be purchased by the customer, while ACM certificated are free. I have done a simple modification to the quickstart template, replacing the SSLCertificateName parameter with SSLCertificateArn, allowing customer to use both IAM and ACM certificates.

Changed from Certificate Name to Certificate ARN to be able to use IAM and ACM certificated

---

templates/quickstart-jira-dc-with-vpc.template.yaml
templates/quickstart-jira-dc.template.yaml

This PR updates Jira version to the latest released version and also removes `latest` as possible value. Using `latest` was problematic in the template in case the stack had autoscaling enabled and might end up in a situation that the newly created node had a different version installed.

DCD-98: Update Jira version to 7.13.1 and remove latest

---

templates/quickstart-jira-dc-with-vpc.template.yaml
templates/quickstart-jira-dc.template.yaml

* removed duplicated `StartCollectd` description
* add `JiraVersion` details to explain that ServiceDesk has different versioning scheme

Update parameter descriptions in Jira quickstarts

---

templates/quickstart-jira-dc.template.yaml

AMIs are built from 9720ed547d8f84e0b7d1e50b6889e98627efecbc commit
*Description of changes:*
New AMIs resolving potential issues with version to download:
For details, please see:
https://bitbucket.org/atlassian/atlassian-aws-deployment/pull-requests/276
https://bitbucket.org/atlassian/atlassian-aws-deployment/pull-requests/277

DCD-206: Update Jira AMI IDs with support for the new download backends

---

templates/quickstart-jira-dc.template.yaml

More information: https://alas.aws.amazon.com/ALAS-2019-1205.html
https://bitbucket.org/atlassian/atlassian-aws-deployment/pull-requests/304

DCD-345: Update AMIs kernel version to `4.14.114-83.126.amzn1.x86_64`

---

ci/quickstart-jira-dc-params.json

Adds a valid S3 prefix to taskcat ci parameters

fixes failing taskcat build as  S3 prefix is not valid

---

templates/quickstart-jira-dc-with-vpc.template.yaml
templates/quickstart-jira-dc.template.yaml

Adds an 3-way switch to enable and configure CloudWatch with optional log aggregation. The actual agent installation/config is performed in the Ansible playbooks.

DCD-436: Enable installation and configuration of CloudWatch agent.

---

templates/quickstart-jira-dc.template.yaml

Adds a basic dashboard with every stack.
Additionally, This PR brings in a few small tuning to a couple of JVM parameters..

Create CloudWatch Dashboard When CloudWatch Integration Is Enabled

---

ci/params/ssl-and-dns/quickstart-jira-ci-params.json
templates/quickstart-jira-dc-with-vpc.template.yaml
templates/quickstart-jira-dc.template.yaml

* Move to ALB instead of classic load balancer
* Add a redirect from port 80 to port 443 if HTTPS is enabled
* Set tomcat scheme based on whether SSL certificate is set (remove tomcat scheme param)

Use ALB instead of Classic Load Balancer

---

templates/quickstart-jira-dc.template.yaml

*Description of changes:*
Included updates to the master Jira templates to support GovCloud configuration. Changes include differences in S3 URL structure and ARN policy structure. Also updated AMIs available for the Amazon Linux 2 instance that are available in GovCloud regions. This has been tested and works in a new GovCloud region. Please note that the RDS instance class size needs to be of the db.m4 family size instead of the default db.m5 class which is not available in GovCloud currently. 

Included updates to the master Jira templates to support GovCloud

---

templates/quickstart-jira-dc-with-vpc.template.yaml
templates/quickstart-jira-dc.template.yaml

Imports the private IP of the bastion host from the ASI so that when CidrBlock is set the Bastion can still SSH to the webserver.

Make webservers accessible for ssh from bastion

---

templates/quickstart-jira-dc-with-vpc.template.yaml
templates/quickstart-jira-dc.template.yaml

Proposed code changes for using SSM param approach
**Code changes that will:**
- Create a new SSM resource, `AnsibleRepoPinSHA`, that is tied to its associated stack and is initially set with a value of: `latest`
- Provide a new IAM policy so that the value of the `AnsibleRepoPinSHA` resource can be updated
- Check the value of `AnsibleRepoPinSHA` (via cfn Init script) if `latest` update the value to the current `HEAD` `SHA`
- New nodes that join the cluster (on an update) will check the value of `AnsibleRepoPinSHA` and utilize the `SHA` it has been set with
- Checkout `dc-deployments-repo` to the `SHA`
**Assumptions**
- To perform an upgrade of the stack using a different `SHA`, the value assigned to `AnsibleRepoPinSHA` will first need to be manually updated to the favored `SHA` via the …

DCD-972: DCD Deployments automation repo pinning

---

README.md
templates/quickstart-jira-dc-with-vpc.template.yaml
templates/quickstart-jira-dc.template.yaml

As this is a custom template change specifically for Trebuchet we have removed the `TomcatConnectionTimeout` within `quickstart-jira-dc-with-vpc.template.yaml` so that we do not exceed the 60 parameter limit. This value is defaulted to `20000` in `quickstart-jira-dc.template.yaml`

CHET-298: Allow users to select the Postgres engine

---

templates/quickstart-jira-dc.template.yaml

Ran custom Jira CI plan (temporarily updated Jira submodules to point to updated quickstart-atlassian-services and updated quickstart-amazon-aurora) results for which are below:
https://server-syd-bamboo.internal.atlassian.com/browse/DCD-AWSJIRA64-JSMOKDEPLOY-9/log
Deploys passed and all but the HTTP acceptance tests which I believe to be a dud (looking at the logs). This run should confirm these AWS partition changes across the board for Jira and the other products; BB, Connie, Crowd
These changes have also been tested in a Gov account and are shown to work, where we no longer have failing deployments

DCD-1051: Gov arn for gov region

---

ci/params/dbVersions/quickstart-jira-aurora-10.json
ci/params/dbVersions/quickstart-jira-aurora-11.json
ci/params/dbVersions/quickstart-jira-aurora-9.json
ci/params/dbVersions/quickstart-jira-postgres-10.json
ci/params/dbVersions/quickstart-jira-postgres-11.json
ci/params/dbVersions/quickstart-jira-postgres-9.json
ci/params/dbVersions/taskcat.yml
templates/quickstart-jira-dc-with-vpc.template.yaml
templates/quickstart-jira-dc.template.yaml

* Add support for Postgres 12
* Make Postgres 11 default database engine (latest supported by Jira)

February Quick Start update

---

templates/quickstart-jira-dc-with-vpc.template.yaml
templates/quickstart-jira-dc.template.yaml

*DCD-1211 Update PostgreSQL version used in AWS QS due to 9.6 EOL*
Added and set by default Postgres 12 (according to Jira 8.20 LTS)

Update PostgreSQL version used in AWS QS due to 9.6 EOL

---

ci/params/aurora/quickstart-jira-dc-aurora-params.json
ci/params/default/quickstart-jira-default-params.json
ci/params/ssl-and-dns/quickstart-jira-ci-params.json
templates/quickstart-jira-dc.template.yaml

*DCD-1354*
- Eliminate unused KMS actions on AWS Quickstart
- Enable the DeploymentAutomationBranch override

DCD-1354 Eliminate unused KMS actions on AWS Quickstart
